<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'grid' => array( 'snippet',
'dashboard-item',
'dashboard-item1',
'dashboard-item2' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'username_button' ),
'top' => array(  ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'snippet' => 'grid',
'dashboard-item' => 'grid',
'dashboard-item1' => 'grid',
'dashboard-item2' => 'grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'username_button' => 'supertop' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'username_button' => array( 'username_button' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'dashboard-item' => array( 'dashboard-item',
'dashboard-item1',
'dashboard-item2' ),
'snippet' => array( 'snippet' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'enrollment_count_by_unit_and_batch',
'dashType' => 0,
'dashName' => 'enrollment_count_by_unit_and_batch_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'users' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'elementName' => 'enrollment_count_by_unit_and_batch_grid',
'table' => 'enrollment_count_by_unit_and_batch',
'type' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'Enrollment Distribution by Home College and Total Number of Units Enrolled',
'dashType' => 0,
'dashName' => 'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'building' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'elementName' => 'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_grid',
'table' => 'Enrollment Distribution by Home College and Total Number of Units Enrolled',
'type' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'Enrollment Status Distribution',
'dashType' => 1,
'dashName' => 'Enrollment_Status_Distribution_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'pie-chart' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'elementName' => 'Enrollment_Status_Distribution_chart',
'table' => 'Enrollment Status Distribution',
'type' => 1,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ) ) ),
'dashSearch' => array( 'searchFields' => array( 'public_student_enlistments_Chart_term_id' => array( array( 'field' => 'term_id',
'table' => 'Enrollment Status Distribution' ) ),
'public_student_enlistments_Chart_status' => array( array( 'field' => 'status',
'table' => 'Enrollment Status Distribution' ) ),
'public_student_enlistments_Chart_count' => array( array( 'field' => 'count',
'table' => 'Enrollment Status Distribution' ) ),
'enrollment_count_by_unit_and_batch_term_id' => array( array( 'field' => 'term_id',
'table' => 'enrollment_count_by_unit_and_batch' ) ),
'enrollment_count_by_unit_and_batch_0_units' => array( array( 'field' => '0 units',
'table' => 'enrollment_count_by_unit_and_batch' ) ),
'enrollment_count_by_unit_and_batch_1_2_units' => array( array( 'field' => '1-2 units',
'table' => 'enrollment_count_by_unit_and_batch' ) ),
'enrollment_count_by_unit_and_batch_3_5_units' => array( array( 'field' => '3-5 units',
'table' => 'enrollment_count_by_unit_and_batch' ) ),
'enrollment_count_by_unit_and_batch_6_8_units' => array( array( 'field' => '6-8 units',
'table' => 'enrollment_count_by_unit_and_batch' ) ),
'enrollment_count_by_unit_and_batch_9_11_units' => array( array( 'field' => '9-11 units',
'table' => 'enrollment_count_by_unit_and_batch' ) ),
'enrollment_count_by_unit_and_batch_12_14_units' => array( array( 'field' => '12-14 units',
'table' => 'enrollment_count_by_unit_and_batch' ) ),
'enrollment_count_by_unit_and_batch_15_units_above' => array( array( 'field' => '15 units above',
'table' => 'enrollment_count_by_unit_and_batch' ) ),
'enrollment_count_by_unit_and_batch_total' => array( array( 'field' => 'total',
'table' => 'enrollment_count_by_unit_and_batch' ) ),
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_0_units' => array( array( 'field' => '0 units',
'table' => 'Enrollment Distribution by Home College and Total Number of Units Enrolled' ) ),
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_1_2_units' => array( array( 'field' => '1-2 units',
'table' => 'Enrollment Distribution by Home College and Total Number of Units Enrolled' ) ),
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_3_5_units' => array( array( 'field' => '3-5 units',
'table' => 'Enrollment Distribution by Home College and Total Number of Units Enrolled' ) ),
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_6_8_units' => array( array( 'field' => '6-8 units',
'table' => 'Enrollment Distribution by Home College and Total Number of Units Enrolled' ) ),
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_9_11_units' => array( array( 'field' => '9-11 units',
'table' => 'Enrollment Distribution by Home College and Total Number of Units Enrolled' ) ),
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_12_14_units' => array( array( 'field' => '12-14 units',
'table' => 'Enrollment Distribution by Home College and Total Number of Units Enrolled' ) ),
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_15_units_above' => array( array( 'field' => '15 units above',
'table' => 'Enrollment Distribution by Home College and Total Number of Units Enrolled' ) ),
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_total' => array( array( 'field' => 'total',
'table' => 'Enrollment Distribution by Home College and Total Number of Units Enrolled' ) ),
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_term_id' => array( array( 'field' => 'term_id',
'table' => 'Enrollment Distribution by Home College and Total Number of Units Enrolled' ) ) ),
'allSearchFields' => array( 'public_student_enlistments_Chart_term_id',
'public_student_enlistments_Chart_status',
'public_student_enlistments_Chart_count',
'enrollment_count_by_unit_and_batch_term_id',
'enrollment_count_by_unit_and_batch_0_units',
'enrollment_count_by_unit_and_batch_1_2_units',
'enrollment_count_by_unit_and_batch_3_5_units',
'enrollment_count_by_unit_and_batch_6_8_units',
'enrollment_count_by_unit_and_batch_9_11_units',
'enrollment_count_by_unit_and_batch_12_14_units',
'enrollment_count_by_unit_and_batch_15_units_above',
'enrollment_count_by_unit_and_batch_total',
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_0_units',
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_1_2_units',
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_3_5_units',
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_6_8_units',
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_9_11_units',
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_12_14_units',
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_15_units_above',
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_total',
'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_term_id' ),
'googleLikeFields' => array( 'public_student_enlistments_Chart_term_id',
'public_student_enlistments_Chart_status' ) ) );
			$pageArray = array( 'id' => 'dashboard',
'type' => 'dashboard',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ) ) ),
array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'snippet' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'dashboard-item' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'dashboard-item1' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'dashboard-item2' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link' ) ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'dashboard-item' => array( 'type' => 'dashboard-item',
'table' => 'enrollment_count_by_unit_and_batch',
'dashType' => 0,
'dashName' => 'enrollment_count_by_unit_and_batch_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'users' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'snippet' => array( 'eventId' => 'Dashboard_snippet',
'label' => array( 'text' => 'Dashboard_snippet',
'type' => 0 ),
'type' => 'snippet' ),
'dashboard-item1' => array( 'type' => 'dashboard-item',
'table' => 'Enrollment Status Distribution',
'dashType' => 1,
'dashName' => 'Enrollment_Status_Distribution_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'pie-chart' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'dashboard-item2' => array( 'type' => 'dashboard-item',
'table' => 'Enrollment Distribution by Home College and Total Number of Units Enrolled',
'dashType' => 0,
'dashName' => 'Enrollment_Distribution_by_Home_College_and_Total_Number_of_Units_Enrolled_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'building' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>